name: Publish to GitHub Packages

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.1

      - name: Setup node with pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

#      - name: Config npm
#        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc

      - name: Publish to NPM
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#        run: pnpm -r publish --no-git-checks --access public

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${GITHUB_TOKEN}
        with:
          minor-wording: 'major'
          major-wording: 'minor'
          patch-wording: 'patch'