name: Publish to GitHub Packages

env:
  PNPM_TOKEN: ${{ secrets.PNPM_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.7.0
          
      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Publish to GitHub Packages
        run: pnpm -r publish --no-git-checks --access public
        env:
          NPM_TOKEN: ${{ secrets.$PNPM_TOKEN }}